// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/codeedge/go-lib/tests/wire/internal/config"
	"github.com/codeedge/go-lib/tests/wire/internal/db"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	sqlDB, cleanup, err := db.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dao := db.NewDao(sqlDB)
	app := NewApp(dao)
	return app, func() {
		cleanup()
	}, nil
}
